### PR TITLE
Automatically update dependencies 

### PR DESCRIPTION
**Pull request by prince-chrismc**
## PR Checklist

- [ ] I've built the code `cargo build`. For major changes, `cargo build --workspace --release` is recommended.
- [ ] I've run the automated unit tests `cargo test`. This executes our automated unit tests.
- [ ] I've not broken any existing tests or functionality. In addition to `cargo test`, I've run `cargo clippy`
- [ ] I've not introduced any new known security vulnerabilities. I've run `cargo audit`

- [ ] I've included a brief description and a good title of the proposed changes and how to test them.
- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [ ] I've associated an [issue](https://github.com/pyrsia/pyrsia/issues) with this Pull Request. 
- [x] I've checked that the code is up-to-date with the `pyrsia/main` branch.
- [ ] I've read ["What is a Good PR?"](good_pr.md)
- [x] I've assigned this Pull Request to "pyrsia/collaborators"

## Description

I just discovered cargo was supported so here's a first pass. It's unclear if it can handle nested `Cargo.toml` but this is a cool start 😎

### CODE REVIEW

**Comment by MitaliBo** [comment]
This is nice feature , since we are enabling version update from dependobot we should also enable security update from the same in order to get informed if the bumped version is vulnerable or not

**Comment by prince-chrismc** [comment]
Ones this is merged I can enable those settings! Great ideal 🚀

**Review by MitaliBo — APPROVED** [review]

**Review by sbtaylor15 — APPROVED** [review]
Looks good.  Should be interesting is what the dependabot finds.

**Comment by prince-chrismc** [comment]
> Looks good. Should be interesting is what the dependabot finds.

A lot 

I use https://marketplace.visualstudio.com/items?itemName=serayuzgur.crates

**Pull request merged**
