### PR TITLE
Prepend "library/" to image names for build and search

### PR DESCRIPTION
**Pull request by ihcomega56**
## Description

Closes pyrsia/pyrsia#1216

prepend `library/` to image names when adding records to or searching transparency log for consistency. It affects the following functions:

- CLI `pyrsia build docker`
- CLI `pyrsia inspect-log docker` - **Note:** All inspect logs which were recorded without `library/` until now would be ignored and would not come up any more after this PR is merged.
- API `/v2/library/<image name>/manifests/<tag>`
- API `/v2/library/<image name>/blobs/<tag>`

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/community/get_involved/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).

### Code Contributions

- [x] I've run [pre-commit.sh](https://github.com/pyrsia/pyrsia/blob/main/pre-commit.sh) ([pre-commit.bat](https://github.com/pyrsia/pyrsia/blob/main/pre-commit.bat)) successfully.
- [x] I've run the [integrations tests](https://github.com/pyrsia/pyrsia-integration-tests#how-to-set-up-and-run-the-tests)
on the PR branch and all tests passes.

### CODE REVIEW

**Review by dasmanas — COMMENTED** [review]
- adding `library` is redundant data
- `library` is also not providing any distinctive information
- Also backward compatibility of transaction log needs to be in purview. when we are saying in the `inspect-log` is not going to show data without library appended in front of it. In future this kind of changes will be more disruptive effect as soon as more strings are attached.

**Review by fishseabowl — COMMENTED** [review]
I also agree with @dasmanas' comment. `library/` may cause more confusion. Refer to [Docker Image Specification v1.1.0](https://github.com/moby/moby/blob/master/image/spec/v1.1.md), the name of a specific Docker image consists of two parts: repository and tag. 
```
[image name] = [repository]:[tag]
```
`library/` is not part of the repository.

**Review by sbtaylor15 — APPROVED** [review]
/lgtm

**Comment by ihcomega56** [comment]
@fishseabowl I was reconsidering it, and came to think this PR is okay to go.
Image names with `library/` are stored as `package_specific_id`. We can decide what this id is like and it does not need to completely follow the specification of Docker image.

**Review by dasmanas — APPROVED** [review]

**Pull request merged**
