### PR TITLE
Fix clippy warnings/errors in PR #978 and PR #979

### PR DESCRIPTION
**Pull request by fishseabowl**
## Description

Fixes pyrsia/pyrsia#980

This PR fixes clipping warnings/errors to unblock github actions.

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/get_involved/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).

### Code Contributions

- [x] I've built the code `cargo build --all-targets` successfully.
- [x] I've run the unit tests `cargo test --workspace` and everything passes.
- [x] I've made sure my rust toolchain is current `rustup update`.

### CODE REVIEW

**Comment by betarelease** [comment]
How did this break? We run clippy on each PR. Can you point to a place where clippy errors went unnoticed and we had to fix them? @fishseabowl

**Comment by fishseabowl** [comment]
> How did this break? We run clippy on each PR. Can you point to a place where clippy errors went unnoticed and we had to fix them? @fishseabowl

Details are in issue #980. These warning/errors are reported on PR #978 and PR #979.

**Review by sbtaylor15 — APPROVED** [review]
/lgtm

**Review by dasmanas — APPROVED** [review]
lgtm

**Pull request merged**
