### PR TITLE
Outline for a demo script CI workflow

### PR DESCRIPTION
**Pull request by prince-chrismc**

### CODE REVIEW

**Comment by sbtaylor15** [comment]
We should hold off on this until the website is up and running all the way since the url path name will change slightly.

**Comment by prince-chrismc** [comment]
But the old one should still be working? Adding a CNAME should remove the original A record?

**Comment by sbtaylor15** [comment]
Yes, the old one will still work.  Here are the [instructions](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages) for the CNAME setup.

**Review by sbtaylor15 — APPROVED** [review]
No changes needed now.  We will need to update the urls once the final website location is up and running.

**Review by betarelease — APPROVED** [review]

**Pull request merged**
