### PR TITLE
Exclude test code from tarpaulin & codcov

### PR DESCRIPTION
**Pull request by dasmanas**
## Description

Fixes [#981](https://github.com/pyrsia/pyrsia/issues/981)

This PR excludes test modules (i.e. the section of test code) from code coverage. This is accomplished by by adding `#[cfg(not(tarpaulin_include))]` to all test modules. See also section **Ignoring code in files** from [cargo-tarpaulin](https://crates.io/crates/cargo-tarpaulin). Below is the sample code snippet how the test module should look like to avoid the test code to be part of Code Coverage.

```
#[cfg(test)]
#[cfg(not(tarpaulin_include))]
mod tests {
    //your test functions and code here
}
```

## Screenshots (optional)
code_coverage_settings_change_impact_demo1

code_coverage_settings_change_impact_demo2

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/get_involved/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).

### Code Contributions

- [x] I've built the code `cargo build --all-targets` successfully.
- [x] I've run the unit tests `cargo test --workspace` and everything passes.
- [x] I've made sure my rust toolchain is current `rustup update`.

### CODE REVIEW

**Comment by dasmanas** [comment]
With the exiting docker `CodeCoverage.Dockerfile` can't run `cargo tarpaulin --workspace`. 

I was getting error **build failed to run custom build command for prost-build v#.#.#**. To solve that we need to install protobuf-compiler.
Additional package `apt-get -y install protobuf-compiler`

**Comment by dasmanas** [comment]
After solving https://github.com/pyrsia/pyrsia/pull/984#issuecomment-1220100798, getting following error.
```
error: failed to run custom build command for `pyrsia_cli v0.1.1 (/home/pyrsia/pyrsia_cli)`

Caused by:
  process didn't exit successfully: `/home/pyrsia/target/debug/build/pyrsia_cli-d1e416be4a2bfbb7/build-script-build` (exit status: 1)
  --- stderr
  Error: could not find repository from '/home/pyrsia/pyrsia_cli'; class=Repository (6); code=NotFound (-3)
warning: build failed, waiting for other jobs to finish...
Aug 18 22:40:25.478 ERROR cargo_tarpaulin: Cargo failed to run! Error: cargo run failed
Error: "Cargo failed to run! Error: cargo run failed"
```

**Comment by dasmanas** [comment]
> After solving [#984 (comment)](https://github.com/pyrsia/pyrsia/pull/984#issuecomment-1220100798), getting following error.
> 
> ```
> error: failed to run custom build command for `pyrsia_cli v0.1.1 (/home/pyrsia/pyrsia_cli)`
> 
> Caused by:
>   process didn't exit successfully: `/home/pyrsia/target/debug/build/pyrsia_cli-d1e416be4a2bfbb7/build-script-build` (exit status: 1)
>   --- stderr
>   Error: could not find repository from '/home/pyrsia/pyrsia_cli'; class=Repository (6); code=NotFound (-3)
> warning: build failed, waiting for other jobs to finish...
> Aug 18 22:40:25.478 ERROR cargo_tarpaulin: Cargo failed to run! Error: cargo run failed
> Error: "Cargo failed to run! Error: cargo run failed"
> ```

Root cause of the issue is .git directory was not included, causes cargo build failure. `.git` has been removed from `.dockerignore` file.

**Comment by dasmanas** [comment]
```
ERROR cargo_tarpaulin: Failed to run tests: ASLR disable failed: EPERM: Operation not permitted
Error: "Failed to run tests: ASLR disable failed: EPERM: Operation not permitted"
ERROR cargo_tarpaulin: Failed to get test coverage! Error: Failed to run tests: Unexpected signal when starting test
Error: "Failed to get test coverage! Error: Failed to run tests: Unexpected signal when starting test"
```

Resolved by turning off seccomp confinement for the container. https://docs.docker.com/engine/reference/run/#security-configuration

**Review by erwin1 — APPROVED** [review]

**Review by fishseabowl — COMMENTED** [review]
Looks good, but excluding unit tests, our codecov is only around 54% 😢

**Comment by erwin1** [comment]
> Looks good, but excluding unit tests, our codecov is only around 54% 😢

I guess we have to take this hit now and gradually improve moving forward.

**Review by fishseabowl — APPROVED** [review]
lgtm

**Pull request merged**
