### PR TITLE
Bump assay crate for security fix

### LINKED ISSUE #397: "assay" using deprecated crate
**Option 1:** assay crate uses deprecated "tempdir" crate which signals warning in "cargo audit". I have created a PR against that crate to replace that with "tempfile", once that is merged  and released, we can upgrade here.

PR created against assay crate : https://github.com/mgattozzi/assay/pull/6

**Option 2:** We can also look for other crates which provides same kind of functionality or have programmed teardown and setup using catch_unwind, i tried this approach but much success 
https://medium.com/@ericdreichert/test-setup-and-teardown-in-rust-without-a-framework-ba32d97aa5ab

**Option 3:** wait until we have setup and teardown capability to be in rust custom frameworks

### PR DESCRIPTION
**Pull request by MitaliBo**
## PR Checklist

- [x] I've built the code `cargo build`. For major changes, `cargo build --workspace --release` is recommended.
- [x] I've run the automated unit tests `cargo test`. This executes our automated unit tests.
- [x] I've not broken any existing tests or functionality. In addition to `cargo test`, I've run `cargo clippy`
- [x] I've not introduced any new known security vulnerabilities. I've run `cargo audit`

- [x] I've included a brief description and a good title of the proposed changes and how to test them.
- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've associated an [issue](https://github.com/pyrsia/pyrsia/issues) with this Pull Request. 
- [x] I've checked that the code is up-to-date with the `pyrsia/main` branch.
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/good_pr.md)
- [x] I've assigned this Pull Request to "pyrsia/collaborators"

## Description

Fixes #397

This PR fixes the security warning generated due to "assay" crate  using deprecated "tempdir" crate. Since i had raised PR with assay (https://github.com/mgattozzi/assay/pull/6) with updated codebase using "tempfile"and it got released so we can upgrade

### CODE REVIEW

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Can you please link to the upstream PR you submitted I would love to keep track of these!

**Comment by MitaliBo** [comment]
> Can you please link to the upstream PR you submitted I would love to keep track of these!

I already have upstream PR mentioned in the linked issue #397 "https://github.com/mgattozzi/assay/pull/6", but i am not sure if i can link any other repo PR here.

**Review by sbtaylor15 — APPROVED** [review]
/lgtm - glad the upstream accepted the changes so quickly

**Review by betarelease — APPROVED** [review]

**Review by sbtaylor15 — APPROVED** [review]
/lgtm

**Comment by prince-chrismc** [comment]
> I already have upstream PR mentioned in the linked issue

Ahh I didn't look there, thanks for sharing ☺️

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
