### PR TITLE
#373 Adds ability to automate developer tasks

### PR DESCRIPTION
**Pull request by betarelease**
- adds a command chain to run the ci process locally before commit/PR

## PR Checklist

- [x] I've built the code `cargo build`. For major changes, `cargo build --workspace --release` is recommended.
- [x] I've run the automated unit tests `cargo test`. This executes our automated unit tests.
- [x] I've not broken any existing tests or functionality. In addition to `cargo test`, I've run `cargo clippy`
- [x] I've not introduced any new known security vulnerabilities. I've run `cargo audit`

- [x] I've included a brief description and a good title of the proposed changes and how to test them.
- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've associated an [issue](https://github.com/pyrsia/pyrsia/issues) with this Pull Request. 
- [x] I've checked that the code is up-to-date with the `pyrsia/main` branch.
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/good_pr.md)
- [x] I've assigned this Pull Request to "pyrsia/collaborators"

## Description

Fixes pyrsia/pyrsia#373

Adds ability to automate developer tasks

### CODE REVIEW

**Comment by betarelease** [comment]
Since @johanvos and @prince-chrismc were the original reviewers on my previous PR I have manually added you here.

**Comment by prince-chrismc** [comment]
There's even more vulnerabilities now 💥

**Comment by prince-chrismc** [comment]
Same two comments

- https://github.com/pyrsia/pyrsia/pull/374#issuecomment-1049066401 (PR title)
- https://github.com/pyrsia/pyrsia/pull/374#issuecomment-1049327572 (docs)

**Comment by betarelease** [comment]
I am looking into the vulnerabilities:

assay -> tempdir (so maybe assay is not a good option) - but it exists in main and does not fail for tempdir vuln
For the others as we discussed, since cargo-make is a dev-dependency it is ok to fail audit-check

I found this PR merged with cargo-audit for ignoring dev-dependencies - https://github.com/rust-lang/cargo/pull/5012. How can we turn this on for our cargo-audit?

**Comment by prince-chrismc** [comment]
> I found this PR merged with cargo-audit for ignoring dev-dependencies - [rust-lang/cargo#5012](https://github.com/rust-lang/cargo/pull/5012).

Just to repeat so we are on the same page... That PR is for cargo in general not the audit tool from [RustSec](https://github.com/rustsec/rustsec) that's flagging the problem. In other words, there's "experimental" support in rust but not yet in the security tooling.

> How can we turn this on for our cargo-audit?

There's no easy way to pipe this in without it introducing some inconsistency AFAIK. Open to ideas.

➡️ here's the audit tool's behavior https://github.com/rustsec/rustsec/blob/1461a59311e93a6692decd98aa325166bfb9322e/cargo-audit/src/auditor.rs#L130-L133

We _could_ delete our lockfile and regenerate a new one (with the experimental flags) but it would contain the latest version of all the packages but given how behind we are (see #382 or #386) and some dont compile... it's not a guarantee to work.
It could also pull in a new version which is compromised, a false positive, which is more confusing.

**Comment by betarelease** [comment]
You are right. My google foo is failing due to `cargo audit` and `cargo-audit` and how google does not understand the difference.

I found a relevant issue that someone raised with cargo-audit on their gihub - https://github.com/rustsec/rustsec/issues/501

**Comment by betarelease** [comment]
I feel like this is really important automation we should add in some way so that everyone on the team runs the same exact steps without having to remember all the -- options in the correct order. 

`cargo-make` makes it possible and easy. How else should we move forward? I would like something that is committed to the codebase instead of in the documentation on the PR template.

**Comment by betarelease** [comment]
@prince-chrismc and I discussed the concerns around `cargo-make` and how heavy it is (plus adds vulnerabilities).

Although we agreed on automation required to keep the dev/PR process simple.

As a result we will not use `cargo-make` and will close this PR. 

But will work on a simpler(maybe simple bash script) to automate the steps we all need to run before submitting a PR.

**Pull request closed without merging**
