### PR TITLE
Always request review from team with dependabot

### PR DESCRIPTION
**Pull request by prince-chrismc**
## Description

Just a small automation so it's not manual

### CODE REVIEW

**Comment by johanvos** [comment]
This looks good to me. I wonder how you test this -- is there a way to test this without integrating (just curious)?

**Comment by prince-chrismc** [comment]
Great question!

I use my personal account to play around with things for the most part. 🔧 
The limitation I found here was because I commented on an issue 🍀 but usually not so lucky.

Given the organization level permissions and projects... there's a fair bit of trial and error (i.e merging and follow up PRs). there's no easy way to recreate our projects to have an environment to test without doing the work 🤷 

Hopefully we have a full time DevOps Engineer who can work on that 🤞

**Comment by prince-chrismc** [comment]
You can see my testing over at https://github.com/prince-chrismc/conan-center-index/actions/workflows/test.yml 😉

**Review by sbtaylor15 — COMMENTED** [review]
@prince-chrismc - should we be consistent and use pyrsia/collaborators for the reviewers, since that is what we use for the other PRs?

**Review by betarelease — DISMISSED** [review]

**Comment by prince-chrismc** [comment]
> should we be consistent and use pyrsia/collaborators for the reviewers, since that is what we use for the other PRs?

Excellent catch! Bad copy pasting thank you 🤗

**Review by efrisch — APPROVED** [review]
👍

**Review by betarelease — APPROVED** [review]

**Pull request merged**
