### PR TITLE
Config with default value when null

### PR DESCRIPTION
**Pull request by dasmanas**
## Description

Closes pyrsia/pyrsia#1106

This PR enables config wizard (i.e. `pyrsia config edit`) to proceed with default value when value is not given by the user. The PR depends on https://github.com/pyrsia/pyrsia/pull/1309. Otherwise the default value for disk space 5.84 GB is not going to work.

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/community/get_involved/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).

### Code Contributions

- [x] I've built the code `cargo build --all-targets` successfully.
- [x] I've run the unit tests `cargo test --workspace` and everything passes.
- [x] I've made sure my rust toolchain is current `rustup update`.

### CODE REVIEW

**Comment by erwin1** [comment]
There's an issue with the default value of disk_allocated. It contains an invalid value, so this happens when you accept all defaults:

```
Enter host: [localhost]

Enter port: [7888]

Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB): [5.84 GB]

Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB): [5.84 GB]

```

I think we should change the default to 10 GB. See also #1308

**Review by erwin1 — APPROVED** [review]
approved but we need to merge #1309 first

**Comment by karolh2000** [comment]
@dasmanas One suggestion, when a user enters the storage value we should accept all kinds of input formats: "10GB", "10 GB", "10gB", etc. I'm not saying we should change it in this PR but when you have time please update the validator for this value. Thanks!

**Review by karolh2000 — DISMISSED** [review]

**Review by fishseabowl — APPROVED** [review]
lgtm

**Review by erwin1 — APPROVED** [review]

**Pull request merged**
