### PR TITLE
Docker manifest to package version

### PR DESCRIPTION
**Pull request by mgrand**
This PR closes some holes in processing of manifests to metadata.

### CODE REVIEW

**Review by MitaliBo — APPROVED** [review]
lgtm

**Comment by mgrand** [comment]
This is the next installment in [#186](https://github.com/pyrsia/pyrsia/pull/186). It is not linked to it because merging this should not close that issue.

**Review by fishseabowl — APPROVED** [review]
It's fine with me.

**Review by efrisch — APPROVED** [review]
👍

**Pull request merged**
