### PR TITLE
Assign @pyrsia/collaborators to all PRs

### LINKED ISSUE #738: Non-maintainers can't assign reviewers, add CODEOWNERS
This was a call out from https://github.com/pyrsia/pyrsia/pull/735#issue-1248957997

### PR DESCRIPTION
**Pull request by prince-chrismc**
## Description

Fixes #738 

https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).
- [x] I've requested a review  from `pyrsia/collaborators`.

### CODE REVIEW

**Review by fishseabowl — DISMISSED** [review]

**Review by adamdmharvey — APPROVED** [review]
👍🏻

**Comment by adamdmharvey** [comment]
Quick note: may make sense to bundle with this PR an update to the PR template to remove the checkbox asking users to check they've assigned reviewers? 🤔 

➡️ https://github.com/pyrsia/pyrsia/blob/main/.github/pull_request_template.md

**Review by sbtaylor15 — APPROVED** [review]
/lgtm

**Comment by prince-chrismc** [comment]
> Quick note: may make sense to bundle with this PR an update to the PR template to remove the checkbox asking users to check they've assigned reviewers? 🤔

Excellent call out ✋

**Review by sbtaylor15 — APPROVED** [review]
/lgtm

**Pull request merged**
