### PR TITLE
Integrated cli config file to calculate disk at node

### LINKED ISSUE #487: Total Disk Space Allocated is not being saved
### Steps taken/Steps to reproduce

I needed to allocate more disk space to pyrsia that was already configured.  Performed a remove followed up by an add with the new allocation.  The new allocation size was not saved.

```
root@pyrsia-node-1:/usr/local/bin# pyrsia config  --remove
root@pyrsia-node-1:/usr/local/bin# pyrsia config  --add
Enter host: 
localhost
Enter port: 
7888
Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB): 
1500 GB
Node configuration Saved !!
root@pyrsia-node-1:/usr/local/bin# systemctl restart pyrsia
root@pyrsia-node-1:/usr/local/bin# pyrsia node -s
Connected Peers Count:       0
Artifacts Count:             554
Total Disk Space Allocated:  10.84 GB
Disk Space Used:             25.1328%
```

### Expected Behavior

Expecting `Total Disk Space Allocated: 1500 GB`

### Experienced Instance of the bug

Ubuntu 20.04 on GCP
Pyrsia version is the latest from the apt-get repo.

### PR DESCRIPTION
**Pull request by MitaliBo**
## PR Checklist

- [x] I've built the code `cargo build`. For major changes, `cargo build --workspace --release` is recommended.
- [x] I've run the automated unit tests `cargo test`. This executes our automated unit tests.
- [x] I've not broken any existing tests or functionality. In addition to `cargo test`, I've run `cargo clippy`
- [x] I've not introduced any new known security vulnerabilities. I've run `cargo audit`

- [x] I've included a brief description and a good title of the proposed changes and how to test them.
- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've associated an [issue](https://github.com/pyrsia/pyrsia/issues) with this Pull Request. 
- [x] I've checked that the code is up-to-date with the `pyrsia/main` branch.
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/good_pr.md)
- [x] I've assigned this Pull Request to "pyrsia/collaborators"

## Description

Fixes #487 

This PR integrates cli config file with node to do  disk calculation

## Screenshots (optional)
Screen Shot 2022-03-14 at 11 52 29 PM

### CODE REVIEW

**Review by sbtaylor15 — DISMISSED** [review]
/lgtm - How would you represent 1.5 terabytes for the config.  1500 GB or would 1.5 TB work?

**Review by efrisch — APPROVED** [review]
👍

**Review by chb0github — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Since christian is on vacation I am following up on this PRs

**Review by prince-chrismc — DISMISSED** [review]
LGTM

I think it's a tiny bit odd for the node to use cli code, I think it could have kept the same name, but that's just a nit

It should reflect the "config" is shared

**Review by prince-chrismc — APPROVED** [review]

**Review by sbtaylor15 — APPROVED** [review]
/lgtm

**Pull request merged**
