### PR TITLE
Pyrsia Configuration Edit - Improved

### PR DESCRIPTION
**Pull request by dasmanas**
## Description

Fixes pyrsia/pyrsia#1248

This PR improves the Pyrsia configuration edit experience. Here is the scenario explained.

* you can choose to update config within a interactive  session using `pyrsia config edit `
```
pyrsia config edit   
Enter host: 
..some.host.com
Enter host: 
some.host.com
Enter port: 
98765 
Enter port: 
7890
Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB): 
10gb
Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB): 
12 GB
Node configuration Saved !!
```

* you can also choose to directly update any config or more than one config directly.
*  * Single config edit

```
# editing host
pyrsia config edit --host localhost
Node configuration Saved !!

# editing port
pyrsia config edit --port 7890 
Node configuration Saved !!

# editing disk space allocation
pyrsia config edit --diskspace "12 GB"
Node configuration Saved !!
```

*  * Multiple config edit

```
pyrsia config edit --host localhost --port 7890 --diskspace "10 GB"
Node configuration Saved !!
```

*  * Multiple config edit with validation failure

```
pyrsia config edit --host .some.localhost --port 65536 --diskspace "10GB"
Invalid value for Hostname
Invalid value for Port Number
Invalid value for Disk Allocation
```

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/community/get_involved/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).

### Code Contributions

- [x] I've built the code `cargo build --all-targets` successfully.
- [x] I've run the unit tests `cargo test --workspace` and everything passes.
- [x] I've made sure my rust toolchain is current `rustup update`.

### CODE REVIEW

**Comment by karolh2000** [comment]
@dasmanas This functionality should be covered in the integration tests. Please create an issue so we won't forget to add the tests. Thanks!

**Review by efrisch — APPROVED** [review]
This looks like a marked improvement to me! 👍

**Comment by dasmanas** [comment]
> @dasmanas This functionality should be covered in the integration tests. Please create an issue so we won't forget to add the tests. Thanks!

For integration test [Issue#12](https://github.com/pyrsia/pyrsia-integration-tests/issues/12) has been created.

**Review by fishseabowl — APPROVED** [review]
lgtm

**Pull request merged**
