### PR TITLE
Fix link bugs in readme.(#1025)

### PR DESCRIPTION
**Pull request by ChengYueJia**
## Description

Ref #1018 

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/get_involved/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).

### Code Contributions

- [x] I've built the code `cargo build --all-targets` successfully.
- [x] I've run the unit tests `cargo test --workspace` and everything passes.
- [x] I've made sure my rust toolchain is current `rustup update`.

### CODE REVIEW

**Comment by betarelease** [comment]
Thanks for the quick fix @ChengYueJia. 
I think you found an issue in the way we organize our docs. We are actually taking the docs/ folder and parsing it to our website https://pyrsia.io. 

The links you fixed were indeed broken when you navigate through github project. And your fixes fix them for that view, but it breaks on the website (when I tried manually). I think your PR/suggestions need to be addressed but let me try a couple of options and we can merge this by editing a little bit.

**Comment by ChengYueJia** [comment]
@betarelease I'll waiting for the good news~~

**Review by AbhijithGanesh — COMMENTED** [review]
Thanks for the contribution @ChengYueJia but I don't think these changes affect/change the present readme file! So we might have to close the PR

**Comment by AbhijithGanesh** [comment]
@betarelease This PR doesn't introduce any significant changes, closing the PR!

**Comment by betarelease** [comment]
I will keep this open for a little. Basically we need to take in the changes that @ChengYueJia is suggesting. Just that they work on github and dont work that well on the website or vice versa. I need to test this on website and then confirm that we can take this in.

**Comment by betarelease** [comment]
@ChengYueJia I have not had a chance to test this yet. But will get to it today. (I need to run jekyll and then import a branch of pyrsia so needs a little setup to test).

In the meanwhile, please join our [slack channel](https://join.slack.com/t/cdeliveryfdn/shared_invite/zt-1eryue9cw-9YpgrfIfsTcDS~hGHchURg) and meet the team. Since you are interested in Rust we have a number of areas you can start contributing to.

**Comment by ChengYueJia** [comment]
@betarelease Thanks for invitation. I'm glad to join in :).

**Comment by betarelease** [comment]
Hi @ChengYueJia 

I tested this with the generation of webpages from our docusaurus website. 

Basically I had to test it in two ways as follows:

1. Ensure that these links are indeed broken as you observed on github itself and some of them are. Thanks for catching.
2. Then to verify the proposed fix I built the website by from github.com/pyrsia/pyrsia.github.io repo and used my local pyrsia/ repo to push latest changes to it. Then bring up the website using the instructions on github.com/pyrsia/pyrsia.github.io. Verify that each of those changes work as expected.

I left comments inline to each of your changes and I think we can take 3 of the 4 changes as you made them. Can you please update the PR and I can approve it for merge. 

Thanks for your patience. It was a little tricky to test this out since we have not written down the steps, but I will write them down now.

**Comment by ChengYueJia** [comment]
@betarelease Thanks for your patience and guide. 
I've done the modifies.

**Review by betarelease — APPROVED** [review]

**Review by fishseabowl — APPROVED** [review]

**Pull request merged**
