### PR TITLE
Provision package versions at startup

### PR DESCRIPTION
**Pull request by tiainen**
## Description

Fixes pyrsia/pyrsia#625

When starting up the pyrsia node, provision all the existing package versions that have been stored locally in the metadata manager on the p2p network.

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).
- [x] I've requested a review  from `pyrsia/collaborators`.

### Code Contributions

- [x] I've built the code `cargo build --all-targets` successfully.
- [x] I've run the unit tests `cargo test --workspace` and everything passes.
- [x] I've made sure my rust toolchain is current `rustup update`.

### CODE REVIEW

**Comment by fishseabowl** [comment]
Please add some unit tests. Thanks

Merging [#644](https://codecov.io/gh/pyrsia/pyrsia/pull/644?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=pyrsia) (https://github.com/pyrsia/pyrsia/commit/79475d82ed6188ebdefd228e2921563f74c038de) into [main](https://codecov.io/gh/pyrsia/pyrsia/commit/105b2ed95a0eeaa5739dce8910e2529703d3ce93?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=pyrsia) (https://github.com/pyrsia/pyrsia/commit/105b2ed95a0eeaa5739dce8910e2529703d3ce93) will _decrease_ coverage by 7.03%.
The diff coverage is 27.27%.

**Comment by tiainen** [comment]
> Please add some unit tests. Thanks

I've reverted the change of using `assay`. There seems to be something wrong with the code coverage tool in combination with assay tests.

**Review by prince-chrismc — APPROVED** [review]

**Review by sbtaylor15 — APPROVED** [review]
/lgtm

**Review by fishseabowl — APPROVED** [review]
LGTM

**Pull request merged**
