### PR TITLE
Enable Inclusive Linting

### PR DESCRIPTION
**Pull request by sbtaylor15**
Add linting to ensure we a conforming to inclusive naming guidelines.

See [Inclusive Linting](https://microsoft.github.io/code-with-engineering-playbook/continuous-integration/inclusive-linting/) for details on the action.

### CODE REVIEW

**Comment by sbtaylor15** [comment]
@prince-chrismc - getting this error with the token.   Not sure how to resolve it.  The action is trying to add a comment to the PR.

```
Running woke with reviewdog 🐶 ...
  reviewdog: This GitHub token doesn't have write permission of Review API [1], 
  so reviewdog will report results via logging command [2] and create annotations similar to
  github-pr-check reporter as a fallback.
```

**Comment by prince-chrismc** [comment]
Sounds like the usually lack of permission towards public forks.

- does this action download any code? (e.g `npm install` would)
- does this PR run any code from the repo? (e.g `cargo test`)

**Comment by sbtaylor15** [comment]
The action downloads a golang program to scan the repo for "bad" words.  It does not run the application.
[woke](https://github.com/get-woke/woke) is the program being run.  Then reviewdog is used to make updates to the PR via comments.

**Comment by prince-chrismc** [comment]
Actually looking into the logs, seem like the author actions already made it smart! 🚀 https://github.com/pyrsia/pyrsia/runs/4707393792?check_suite_focus=true#step:3:32

I would much prefer to have this under the "lint" workflow... we can remove the rust name.
The "checks api" from public forks is quite annoying, it leave reports under the wrong action. I would suggest using the https://github.com/get-woke/woke-action-reviewdog#github-pr-review reporter along with the the `"pull_request_target"` it seems safe at first glance 🤞

**Comment by sbtaylor15** [comment]
@prince-chrismc - Is this what you are thinking of for the structure?

**Comment by prince-chrismc** [comment]
Yes ❤️ 

I think we will have permission problems however. Maybe we can merge this an follow up with more adjustments laster?

**Comment by prince-chrismc** [comment]
Does this close #148?

**Review by prince-chrismc — APPROVED** [review]

**Comment by sbtaylor15** [comment]
> Does this close #148?

No, #148 is a "values.md" that says how we approach inclusivity.  That file still needs to be created.

**Review by mgrand — APPROVED** [review]

**Comment by prince-chrismc** [comment]
This is is never being ran 😕 

image

**Pull request merged**
