### PR TITLE
Improve Cloud Sync for Release Archive Listing Generation

### PR DESCRIPTION
**Pull request by dasmanas**
## Description

Fixes pyrsia/pyrsia#

This PR improves the time taken for list generation of installer's release archive by removing the entire rsync from Cloud Bucket to GitHub runner. The `genlisting.py` needs directories and files to be in hierarchically correct place to generate the index.html properly. This has been achieved through `genlistingsyncoptimized.py`. As we are growing our archive sized regularly, this makes the build slower day by day in the rsync process.

Added a new option `dummysync` to the `genlisting.py` to let the script know it is working with a synthetically sync structure. So that ie can read the file size from the content of the file instead of reading the meta or FD of the file.

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/community/get_involved/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).

### Code Contributions

- [x] I've run [pre-commit.sh](https://github.com/pyrsia/pyrsia/blob/main/pre-commit.sh) ([pre-commit.bat](https://github.com/pyrsia/pyrsia/blob/main/pre-commit.bat)) successfully.
- [x] I've run the [integrations tests](https://github.com/pyrsia/pyrsia-integration-tests#how-to-set-up-and-run-the-tests)
on the PR branch and all tests passes.

### CODE REVIEW

**Comment by sbtaylor15** [comment]
@dasmanas please update the chartmuseum.sh to use this optimization as well.  Also let @karolh2000 know on how to use the new optimization.

**Comment by dasmanas** [comment]
> @dasmanas please update the chartmuseum.sh to use this optimization as well. Also let @karolh2000 know on how to use the new optimization.

done too

**Review by sbtaylor15 — DISMISSED** [review]
/lgtm

**Review by sbtaylor15 — APPROVED** [review]
/lgtm

**Comment by betarelease** [comment]
missing the issue number in the description `Fixes pyrsia/pyrsia#`. If there is no issue update to remove this line.

**Review by karolh2000 — APPROVED** [review]

**Review by fishseabowl — APPROVED** [review]

**Pull request merged**
