### PR TITLE
Fix `.deb` creation workflow

### PR DESCRIPTION
**Pull request by prince-chrismc**
- Fixes the changes to paths that were missed in one spot
  - report errors when upload fails
- allow most of the job to run in forks and in PRs so it's easier to spot errors

main is currently failing due to this.

https://github.com/pyrsia/pyrsia/runs/4611820941?check_suite_focus=true#step:5:8

### CODE REVIEW

**Review by sbtaylor15 — CHANGES_REQUESTED** [review]
I believe that we need to have the if: statements to prevent a fork or PR updating the pyrsia/website repo on a successful build.  

@prince-chrismc check the rust action results on prince-chrismc:main to see if pyrsia/website repo was updated or not.  I ran into this at on point in testing.

**Comment by prince-chrismc** [comment]
It still there. I just removed the extras that preventing use form testing and ensuring things work correctly.

Only the actual "upload" is blocked.
https://github.com/prince-chrismc/pyrsia-sandbox/runs/4613194424?check_suite_focus=true

**Review by sbtaylor15 — APPROVED** [review]
No changes needed.  The test run looks good.

**Comment by prince-chrismc** [comment]
The "blocked" steps also applies to PRs here. (again so it's easier to spot issues)

https://github.com/pyrsia/pyrsia/runs/4613299692?check_suite_focus=true

**Review by chb0github — APPROVED** [review]

**Pull request merged**
