### PR TITLE
Hide the nonce from the blockchain structures

### PR DESCRIPTION
**Pull request by prince-chrismc**
## PR Checklist

- [x] I've built the code `cargo build`. For major changes, `cargo build --workspace --release` is recommended.
- [x] I've run the automated unit tests `cargo test`. This executes our automated unit tests.
- [x] I've not broken any existing tests or functionality. In addition to `cargo test`, I've run `cargo clippy`
- [x] I've not introduced any new known security vulnerabilities. I've run `cargo audit`

- [x] I've included a brief description and a good title of the proposed changes and how to test them.
- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've associated an [issue](https://github.com/pyrsia/pyrsia/issues) with this Pull Request. 
- [x] I've checked that the code is up-to-date with the `pyrsia/main` branch.
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/good_pr.md)
- [x] I've assigned this Pull Request to "pyrsia/collaborators"

## Description

~I noticed we still have the skeleton for early POCs where we played with mining.
Since we do not want anything of that confused with our goals I ripped it out!~

The nonce is a "random salt" to harden. It's not required for any consumer so It's not private.

I also fixed some clippy warnings

### CODE REVIEW

**Comment by fishseabowl** [comment]
@prince-chrismc Nonce here is not used for the hash difficulty of mining. Just for security, preventing such as replay attacks  and chosen-plaintext attacks.

**Comment by prince-chrismc** [comment]
After discussion on Zoom...

The usage of `nonce` here is not enough for "replay attacks" however it's still good for "choosen text" where repeat the data + signature can enviably compromise the keys.

We've decide to leave it and I will
- [ ] make a new issue for replay attack
- [ ] revert removing nonce

The PR will only be for the tiny refactors.

**Comment by prince-chrismc** [comment]
After more thought, I decide to hide the nonce from the API, since it should always be random and never be read.

it's less confusing to the user

**Review by fishseabowl — APPROVED** [review]
It looks fine to me.

**Review by chb0github — APPROVED** [review]

**Review by fishseabowl — APPROVED** [review]

**Comment by MitaliBo** [comment]
> After discussion on Zoom...
> 
> The usage of `nonce` here is not enough for "replay attacks" however it's still good for "choosen text" where repeat the data + signature can enviably compromise the keys.
> 
> We've decide to leave it and I will
> 
> * [x]  make a new issue for replay attack
> * [x]  ~revert removing nonce~
> 
> The PR will only be for the tiny refactors.

I was about to put the same for replay attacks but its good we have issue covering for that because that is the main purpose of it.

**Review by MitaliBo — APPROVED** [review]

**Pull request merged**
