### PR TITLE
Prototype of integration testing based on `testcontainers`

### PR DESCRIPTION
**Pull request by dgarus**
Referred to #1454

`pre-commit.sh` builds the `pyrsia/test_node` image, runs tests and removes the image after tests.

The flag `ignore-it` allows ignoring integration tests.

Evolution:
 - Create Dockerfile for tests purposes as test resource.
 - Prepare SQLite db file and copy it into container to test node responses (maybe, is there a better idea?)
 - To test p2p communications between nodes, we should have a test discovery service. Do we have a test discovery service?

### CODE REVIEW

**Comment by betarelease** [comment]
To get this reviewed, please convert this to `ready for review`

**Comment by dgarus** [comment]
> To get this reviewed, please convert this to `ready for review`

Ok

**Comment by dgarus** [comment]
image

https://rustsec.org/advisories/RUSTSEC-2020-0071

Can we use `testcontainer` with this vulnerability if it is used only in a test scope?

**Comment by fishseabowl** [comment]
> image
> 
> https://rustsec.org/advisories/RUSTSEC-2020-0071
> 
> Can we use `testcontainer` with this vulnerability if it is used only in a test scope?

In my opinion it is better to avoid any vulnerability error. Maybe you can try the latest version `time 0.3.19`.

**Review by fishseabowl — COMMENTED** [review]
Some checks failed. It is better to fix it. Thanks

**Comment by dgarus** [comment]
> > image
> > https://rustsec.org/advisories/RUSTSEC-2020-0071
> > Can we use `testcontainer` with this vulnerability if it is used only in a test scope?
> 
> In my opinion it is better to avoid any vulnerability error. Maybe you can try the latest version `time 0.3.19`.

I can't change this

https://github.com/testcontainers/testcontainers-rs/issues/389
```
RUSTSEC-2020-0071 Impact
Unix-like operating systems may segfault due to dereferencing a dangling pointer in specific circumstances. 
```
It doesn't look critical for tests, isn't it?

**Pull request closed without merging**
