### PR TITLE
Preparing Cargo.toml for next release 0.2.4

### PR DESCRIPTION
**Pull request by dasmanas**
## Description

Fixes pyrsia/pyrsia#

This PR prepares cargo.toml for next release

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/community/get_involved/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).

### Code Contributions

- [x] I've run [pre-commit.sh](https://github.com/pyrsia/pyrsia/blob/main/pre-commit.sh) ([pre-commit.bat](https://github.com/pyrsia/pyrsia/blob/main/pre-commit.bat)) successfully.
- [x] I've run the [integrations tests](https://github.com/pyrsia/pyrsia-integration-tests#how-to-set-up-and-run-the-tests)
on the PR branch and all tests passes.

### CODE REVIEW

**Review by ihcomega56 — COMMENTED** [review]
I compared it with the previous version and found that `.github/workflows/rust.yml` is not updated this time. Is it intentional?
https://github.com/pyrsia/pyrsia/pull/1444/files

**Comment by dasmanas** [comment]
> I compared it with the previous version and found that `.github/workflows/rust.yml` is not updated this time. Is it intentional? https://github.com/pyrsia/pyrsia/pull/1444/files

hardcoding has been resolved by #1495 

> I compared it with the previous version and found that `.github/workflows/rust.yml` is not updated this time. Is it intentional? https://github.com/pyrsia/pyrsia/pull/1444/files

all version hardcoding has been resolved by PR #1495

**Review by sbtaylor15 — APPROVED** [review]
/lgtm

**Review by fishseabowl — APPROVED** [review]

**Comment by ihcomega56** [comment]
@dasmanas Thank you for the info!

**Pull request merged**
