### PR TITLE
Fixes PR#1209

### PR DESCRIPTION
**Pull request by dasmanas**
## Description

Fixes the issue introduced by https://github.com/pyrsia/pyrsia/pull/1209.

- with GNU SED
- macos build in native zsh by using `shell: /bin/zsh -e {0}` to all `run`

Releases installer archive in Cloud Bucket under following directory structure.
```
.
├── latest
│   ├── x86_64
│   ├── arm64
├── stable
│   ├── x86_64
│   ├── arm64
```

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/community/get_involved/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).

### Code Contributions

- [x] I've built the code `cargo build --all-targets` successfully.
- [x] I've run the unit tests `cargo test --workspace` and everything passes.
- [x] I've made sure my rust toolchain is current `rustup update`.

### CODE REVIEW

**Review by sbtaylor15 — DISMISSED** [review]
/lgtm

**Review by sbtaylor15 — DISMISSED** [review]
Need to add something similar to the following so the index.html pages are generated with the new tar files listed.
```
gsutil -m rsync -r gs://homebrewrepo .

cp $WORKSPACE/pyrsia-${{ steps.add-fqbvn-and-export.outputs.TAG_NAME }}.tar.gz ${RELTYPE}/${ARCHTYPE}/pyrsia-${FQBVN}.tar.gz

# Generate pretty directory listing web pages
python3 $WORKSPACE/.github/workflows/genlisting.py -r

# copy new public repo to GCS
gsutil -m rsync -r . gs://homebrewrepo
```

**Comment by dasmanas** [comment]
> Need to add something similar to the following so the index.html pages are generated with the new tar files listed.
> 
> ```
> gsutil -m rsync -r gs://homebrewrepo .
> 
> cp $WORKSPACE/pyrsia-${{ steps.add-fqbvn-and-export.outputs.TAG_NAME }}.tar.gz ${RELTYPE}/${ARCHTYPE}/pyrsia-${FQBVN}.tar.gz
> 
> # Generate pretty directory listing web pages
> python3 $WORKSPACE/.github/workflows/genlisting.py -r
> 
> # copy new public repo to GCS
> gsutil -m rsync -r . gs://homebrewrepo
> ```

made required changes
```
mkdir syncdir
gsutil -m cp pyrsia-${FQBVN}.tar.gz  gs://homebrewrepo/${RELTYPE}/${ARCHTYPE}/pyrsia-${FQBVN}.tar.gz
gsutil -m rsync -r gs://homebrewrepo ./syncdir/
python3 .github/workflows/genlisting.py syncdir -r
gsutil -m rsync -r ./syncdir/ gs://homebrewrepo
```

**Comment by dasmanas** [comment]
> > Need to add something similar to the following so the index.html pages are generated with the new tar files listed.
> > ```
> > gsutil -m rsync -r gs://homebrewrepo .
> > 
> > cp $WORKSPACE/pyrsia-${{ steps.add-fqbvn-and-export.outputs.TAG_NAME }}.tar.gz ${RELTYPE}/${ARCHTYPE}/pyrsia-${FQBVN}.tar.gz
> > 
> > # Generate pretty directory listing web pages
> > python3 $WORKSPACE/.github/workflows/genlisting.py -r
> > 
> > # copy new public repo to GCS
> > gsutil -m rsync -r . gs://homebrewrepo
> > ```
> 
> made required changes
> 
> ```
> mkdir syncdir
> gsutil -m cp pyrsia-${FQBVN}.tar.gz  gs://homebrewrepo/${RELTYPE}/${ARCHTYPE}/pyrsia-${FQBVN}.tar.gz
> gsutil -m rsync -r gs://homebrewrepo ./syncdir/
> python3 .github/workflows/genlisting.py syncdir -r
> gsutil -m rsync -r ./syncdir/ gs://homebrewrepo
> ```

With growing number of artifacts, these 2 rsync might take longer in future.

**Review by erwin1 — APPROVED** [review]

**Review by jperedadnr — APPROVED** [review]

**Pull request merged**
